name: ci-v2

on:
  push:
    branches:
      - artnoi.com

jobs:
  build-deploy-pages:
    name: Build GitHub Pages
    uses: ./.github/workflows/pages_v2.yaml
    with:
      dist: ./artnoi.com/dist
      deploy_branch: test-publish/artnoi.com
      wipe_deploy_branch: true
      cname: artnoi.com
     
