name: ci-v2

on:
  push:
    branches:
      - master

jobs:
  build-deploy-pages:
    name: Build GitHub Pages using ssg
    uses: ./.github/workflows/ssg-pages.yaml
    with:
      dist: ./johndoe.com/dist
      deploy_branch: test-pages-workflow/johndoe.com
      wipe_deploy_branch: true
      cname: johndoe.com
