name: webtools-pages

on:
  workflow_call:
    inputs:
      # Site key to build, must be defined in manifest.json
      sitekey:
        type: string
        required: true

      # Create directory before attempting to build HTML
      mkdir:
        type: string
        required: false

      # Target directory
      dist:
        type: string
        required: true

      # Target branch to copy `dist` to
      deploy_branch:
        type: string
        required: true

      # If true, the deploy branch will only contain artifacts from the last commit
      wipe_deploy_branch:
        type: boolean
        required: true

      # Custom domain name. This will create file CNAME at the root of dist to be copied to deploy branch
      cname:
        type: string
        required: false

jobs:
  build:
    name: Build static sites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install python dependencies
        run: pip install htmlmin

      - name: Install lowdown
        run: sudo apt-get install -y lowdown

      - name: Mkdir ${{ inputs.mkdir }}
        if: inputs.mkdir != ''
        run: mkdir -p ${{ inputs.mkdir }}

      - name: Build ${{ inputs.sitekey }}
        run: yes | ./linkweb.sh ${{ inputs.sitekey }} && yes | ./genhtml.sh ${{ inputs.sitekey }}

      # Prepare CNAME for GitHub Pages with custom domain
      - name: CNAME ${{ inputs.cname }}
        if: inputs.cname != ''
        run: echo ${{ inputs.cname }} > ${{ inputs.dist }}/CNAME
        
      - name: Deploy to ${{ inputs.deploy_branch }}
        uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ inputs.deploy_branch }}
          publish_dir: ${{ inputs.dist }}
          force_orphan: $ {{ inputs.wipe_deploy_branch }}
